
FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.1-gpu-py310

RUN pip install -U pip boto3 sagemaker

COPY requirements.txt /opt/ml/packages/
RUN pip install -r /opt/ml/packages/requirements.txt

# 기본 환경변수
ENV PYTHONUNBUFFERED=TRUE
ENV PATH="/opt/ml/code:${PATH}"
ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/code
